/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language, Translation } from './types';

export const translations: Record<Language, Translation> = {
  fr: {
    mainName: "EL MOATADIDE RAYAN",
    title: "Ingénieur en Intelligence Artificielle",
    profileTitle: "Profil",
    profileText: "Étudiant en ingénierie en Intelligence Artificielle, avec une solide formation en leadership et management en collaboration avec la CAF. Fondateur de la startup éducative \"3alem o t3alem\". Certificat professionnel en Intelligence Artificielle obtenu après avoir remporté une compétition nationale sur la meilleure configuration PC optimisée pour DeepSeek R1. Certifié en orientation scolaire avec accompagnement d’élèves dans plus de 10 lycées. Actuellement en formation en entrepreneuriat.",
    educationTitle: "Formation",
    edu1Title: "Étudiant en Intelligence Artificielle",
    edu1Text: "Centre de préparation Al Kendi Oriente vers l’ENIAD (école nationale de l'intelligence Artificielle) à Berkane – 2025/2026",
    edu2Title: "Certificat Professionnel en Intelligence Artificielle",
    edu2Text: "Lauréat d’une compétition nationale sur l’optimisation hardware pour IA avancée (DeepSeek R1).",
    edu3Title: "Formation Union Africaine – CAF",
    edu3Text: "Programme en Communication stratégique, Leadership, Gestion de projets et Management d’équipes.",
    edu4Title: "Certification en Orientation",
    edu4Text: "Encadrement et accompagnement d’élèves dans plus de 10 lycées.",
    edu5Title: "Formation en Entrepreneuriat",
    edu5Text: "En cours – Formation axée sur la création et la gestion de startups, incluant des modules sur l'innovation, le financement et le développement d'entreprises.",
    experienceTitle: "Expérience",
    exp1Title: "Compétition Nationale de Calcul Mental",
    exp1Text: "2ème Prix – Classé parmi les Top 20 au niveau national.",
    exp2Title: "Compétition d’Expression Orale",
    exp2Text: "3ème Prix – Présentation sur le leadership et la motivation.",
    exp3Title: "Organisation – Stade Mohammed V",
    exp3Text: "Responsable de coordination lors de la Coupe d'Afrique au Maroc 2025",
    exp4Title: "Fondateur – 3alem o t3alem",
    exp4Text: "1ère Place – Compétition Startup innovation éducative.",
    exp5Title: "Système de Réservation Hôtelière",
    exp5Text: "Développement d’un système basé sur l’analyse de données et la gestion de bases de données.",
    exp6Title: "Automatisation du Recrutement",
    exp6Text: "Développement d'un outil d'IA pour automatiser le processus de recrutement, incluant l'analyse automatique de CV, la présélection des candidats basée sur des algorithmes d'apprentissage automatique, et l'intégration avec des bases de données RH pour optimiser l'efficacité du recrutement.",
    exp7Title: "Membre de startup – codexa.ma",
    exp7Text: "Développeur spécialisé en Backend, conception d'architectures de base de données robustes, d'APIs performantes et intégration de services d'intelligence artificielle.",
    exp8Title: "Organisation d'Événement International",
    exp8Text: "Organisateur de l'événement mondial de course de fond 'One Run Global Marathon', gestion de la logistique, de la communication stratégique et de la coordination interne.",
    skillsTitle: "Compétences",
    skillsList: ["Web Design", "Développement Front-End", "Gestion de Bases de Données", "Intelligence Artificielle Avancée", "Optimisation Hardware IA", "Leadership & Communication", "Orientation Scolaire"],
    languagesTitle: "Langues",
    languagesList: ["Arabe : Langue maternelle", "Français : Excellent", "Anglais : Excellent", "Espagnol : Débutant"],
    contactTitle: "Contact",
    contactPhone: "+212 717568270",
    contactEmail: "moatadidrayan7@gmail.com",
    contactLocation: "Mohammedia, Béni Yakhlef",
    commentsTitle: "Commentaires",
    namePlaceholder: "Votre nom",
    commentPlaceholder: "Votre commentaire",
    publishButton: "Publier",
    instagramLabel: "Instagram",
    linkedinLabel: "LinkedIn",
    footer: "© 2026 Rayan El Moatadide | Tous droits réservés"
  },
  en: {
    mainName: "EL MOATADIDE RAYAN",
    title: "Artificial Intelligence Engineer",
    profileTitle: "Profile",
    profileText: "Student in Artificial Intelligence engineering, with solid training in leadership and management in collaboration with CAF. Founder of the educational startup \"3alem o t3alem\". Professional certificate in Artificial Intelligence obtained after winning a national competition on the best PC configuration optimized for DeepSeek R1. Certified in school guidance with support for students in more than 10 high schools. Currently in entrepreneurship training.",
    educationTitle: "Education",
    edu1Title: "Student in Artificial Intelligence",
    edu1Text: "Al Kendi Preparation Center Oriented towards ENIAD (National School of Artificial Intelligence) in Berkane – 2025/2026",
    edu2Title: "Professional Certificate in Artificial Intelligence",
    edu2Text: "Winner of a national competition on hardware optimization for advanced AI (DeepSeek R1).",
    edu3Title: "African Union Training – CAF",
    edu3Text: "Program in Strategic Communication, Leadership, Project Management and Team Management.",
    edu4Title: "Certification in Guidance",
    edu4Text: "Supervision and support of students in more than 10 high schools.",
    edu5Title: "Entrepreneurship Training",
    edu5Text: "Ongoing – Training focused on startup creation and management, including modules on innovation, funding, and business development.",
    experienceTitle: "Experience",
    exp1Title: "National Mental Calculation Competition",
    exp1Text: "2nd Prize – Ranked in the Top 20 nationally.",
    exp2Title: "Oral Expression Competition",
    exp2Text: "3rd Prize – Presentation on leadership and motivation.",
    exp3Title: "Organization – Mohammed V Stadium",
    exp3Text: "Coordination manager during the Africa Cup in Morocco 2025",
    exp4Title: "Founder – 3alem o t3alem",
    exp4Text: "1st Place – Educational Innovation Startup Competition.",
    exp5Title: "Hotel Reservation System",
    exp5Text: "Development of a system based on data analysis and database management.",
    exp6Title: "Recruitment Automation",
    exp6Text: "Development of an AI tool to automate the recruitment process, including automatic CV analysis, candidate pre-selection based on machine learning algorithms, and integration with HR databases to optimize recruitment efficiency.",
    exp7Title: "Startup Member – codexa.ma",
    exp7Text: "Developer specialized in Backend, designing robust database architectures, high-performance APIs, and integrating artificial intelligence services.",
    exp8Title: "International Event Organization",
    exp8Text: "Organizer of the global long-distance running event 'One Run Global Marathon', managing logistics, strategic communication, and internal coordination.",
    skillsTitle: "Skills",
    skillsList: ["Web Design", "Front-End Development", "Database Management", "Advanced Artificial Intelligence", "AI Hardware Optimization", "Leadership & Communication", "School Guidance"],
    languagesTitle: "Languages",
    languagesList: ["Arabic: Native", "French: Excellent", "English: Excellent", "Spanish: Beginner"],
    contactTitle: "Contact",
    contactPhone: "+212 717568270",
    contactEmail: "moatadidrayan7@gmail.com",
    contactLocation: "Mohammedia, Béni Yakhlef",
    commentsTitle: "Comments",
    namePlaceholder: "Your name",
    commentPlaceholder: "Your comment",
    publishButton: "Publish",
    instagramLabel: "Instagram",
    linkedinLabel: "LinkedIn",
    footer: "© 2026 Rayan El Moatadide | All rights reserved"
  },
  ar: {
    mainName: "ريان المعتضد",
    title: "مهندس في الذكاء الاصطناعي",
    profileTitle: "الملف الشخصي",
    profileText: "طالب في هندسة الذكاء الاصطناعي، مع تدريب قوي في القيادة والإدارة بالتعاون مع الـ CAF. مؤسس الشركة الناشئة التعليمية \"3alem o t3alem\". شهادة مهنية في الذكاء الاصطناعي حصل عليها بعد الفوز في مسابقة وطنية حول أفضل تكوين حاسوب محسن لـ DeepSeek R1. معتمد في التوجيه المدرسي مع دعم الطلاب في أكثر من 10 ثانويات. حالياً في تدريب على ريادة الأعمال.",
    educationTitle: "التكوين",
    edu1Title: "طالب في الذكاء الاصطناعي",
    edu1Text: "مركز التحضير الكندي موجه نحو ENIAD (المدرسة الوطنية للذكاء الاصطناعي) في بركان – 2025/2026",
    edu2Title: "شهادة مهنية في الذكاء الاصطناعي",
    edu2Text: "فائز في مسابقة وطنية حول تحسين الأجهزة للذكاء الاصطناعي المتقدم (DeepSeek R1).",
    edu3Title: "تدريب الاتحاد الأفريقي – CAF",
    edu3Text: "برنامج في التواصل الاستراتيجي، القيادة، إدارة المشاريع وإدارة الفرق.",
    edu4Title: "شهادة في التوجيه",
    edu4Text: "إشراف ودعم الطلاب في أكثر من 10 ثانويات.",
    edu5Title: "تدريب في ريادة الأعمال",
    edu5Text: "جاري – تدريب يركز على إنشاء الشركات الناشئة وإدارتها، بما في ذلك وحدات حول الابتكار والتمويل وتطوير الأعمال.",
    experienceTitle: "الخبرة",
    exp1Title: "مسابقة وطنية في الحساب الذهني",
    exp1Text: "الجائزة الثانية – مصنف ضمن أفضل 20 على المستوى الوطني.",
    exp2Title: "مسابقة التعبير الشفوي",
    exp2Text: "الجائزة الثالثة – عرض حول القيادة والتحفيز.",
    exp3Title: "التنظيم – ملعب محمد الخامس",
    exp3Text: "مسؤول التنسيق خلال كأس أفريقيا في المغرب 2025",
    exp4Title: "مؤسس – 3alem o t3alem",
    exp4Text: "المركز الأول – مسابقة الابتكار التعليمي للشركات الناشئة.",
    exp5Title: "نظام حجز فندقي",
    exp5Text: "تطوير نظام يعتمد على تحليل البيانات وإدارة قواعد البيانات.",
    exp6Title: "أتمتة التوظيف",
    exp6Text: "تطوير أداة ذكاء اصطناعي لأتمتة عملية التوظيف، بما في ذلك تحليل السير الذاتية التلقائي، واختيار المرشحين مسبقاً بناءً على خوارزميات التعلم الآلي، والتكامل مع قواعد بيانات الموارد البشرية لتحسين كفاءة التوظيف.",
    exp7Title: "عضواً في شركة ناشئة – codexa.ma",
    exp7Text: "مطور متخصص في الواجهة الخلفية (Backend)، وتصميم قواعد بيانات قوية، وتطوير واجهات برمجة تطبيقات (APIs) عالية الأداء ودمج خدمات الذكاء الاصطناعي.",
    exp8Title: "تنظيم حدث دولي",
    exp8Text: "منظم الحدث العالمي للجري 'One Run Global Marathon'، وإدارة اللوجستيات والتواصل الاستراتيجي والتنسيق الداخلي للتظاهرة.",
    skillsTitle: "المهارات",
    skillsList: ["تصميم الويب", "تطوير الواجهة الأمامية", "إدارة قواعد البيانات", "الذكاء الاصطناعي المتقدم", "تحسين أجهزة الذكاء الاصطناعي", "القيادة والتواصل", "التوجيه المدرسي"],
    languagesTitle: "اللغات",
    languagesList: ["العربية: اللغة الأم", "الفرنسية: ممتاز", "الإنجليزية: ممتاز", "الإسبانية: مبتدئ"],
    contactTitle: "الاتصال",
    contactPhone: "+212 717568270",
    contactEmail: "moatadidrayan7@gmail.com",
    contactLocation: "المحمدية، بني يخلف",
    commentsTitle: "التعليقات",
    namePlaceholder: "اسمك",
    commentPlaceholder: "تعليقك",
    publishButton: "نشر",
    instagramLabel: "إنستغرام",
    linkedinLabel: "لينكد إن",
    footer: "© 2026 ريان المعتضد | جميع الحقوق محفوظة"
  },
  es: {
    mainName: "RAYAN EL MOATADIDE",
    title: "Ingeniero en Inteligencia Artificial",
    profileTitle: "Perfil",
    profileText: "Estudiante en ingeniería en Inteligencia Artificial, con una sólida formación en liderazgo y gestión en collaboration con la CAF. Fundador de la startup educativa \"3alem o t3alem\". Certificado profesional en Inteligencia Artificial obtenido después de ganar una competición nacional sobre la mejor configuración de PC optimizada para DeepSeek R1. Certificado en orientación escolar con acompañamiento de alumnos en más de 10 institutos. Actualmente en formación en emprendimiento.",
    educationTitle: "Formación",
    edu1Title: "Estudiante en Inteligencia Artificial",
    edu1Text: "Centro de preparación Al Kendi Orientado hacia ENIAD (Escuela Nacional de Inteligencia Artificial) en Berkane – 2025/2026",
    edu2Title: "Certificado Profesional en Inteligencia Artificial",
    edu2Text: "Ganador de una competición nacional sobre optimización de hardware para IA avanzada (DeepSeek R1).",
    edu3Title: "Formación Unión Africana – CAF",
    edu3Text: "Programa en Comunicación estratégica, Liderazgo, Gestión de proyectos y Gestión de equipos.",
    edu4Title: "Certificación en Orientación",
    edu4Text: "Supervisión y acompañamiento de alumnos en más de 10 institutos.",
    edu5Title: "Formación en Emprendimiento",
    edu5Text: "En curso – Formación enfocada en la creación y gestión de startups, incluyendo módulos sobre innovación, financiamiento y desarrollo de negocios.",
    experienceTitle: "Experiencia",
    exp1Title: "Competición Nacional de Cálculo Mental",
    exp1Text: "2º Premio – Clasificado entre los Top 20 a nivel nacional.",
    exp2Title: "Competición de Expresión Oral",
    exp2Text: "3º Premio – Presentación sobre liderazgo y motivación.",
    exp3Title: "Organización – Estadio Mohammed V",
    exp3Text: "Responsable de coordinación durante la Copa de África en Marruecos 2025",
    exp4Title: "Fundador – 3alem o t3alem",
    exp4Text: "1er Lugar – Competición de Innovación Educativa para Startups.",
    exp5Title: "Sistema de Reserva Hotelera",
    exp5Text: "Desarrollo de un sistema basado en el análisis de datos y la gestión de bases de datos.",
    exp6Title: "Automatisation du Recrutement",
    exp6Text: "Desarrollo de una herramienta de IA para automatizar el proceso de reclutamiento, incluyendo el análisis automático de CV, la preselección de candidatos basada en algoritmos de aprendizaje automático, y la integración con bases de données de RRHH para optimizar l'efficacité du recrutement.",
    exp7Title: "Miembro de Startup – codexa.ma",
    exp7Text: "Desarrollador especializado en Backend, diseño de arquitecturas de bases de datos robustas, APIs de alto rendimiento e integración de servicios de inteligencia artificial.",
    exp8Title: "Organización de Evento Internacional",
    exp8Text: "Organizador del evento mundial de carreras de fondo 'One Run Global Marathon', gestionando la logística, comunicación estratégica y coordinación interna.",
    skillsTitle: "Habilidades",
    skillsList: ["Diseño Web", "Desarrollo Front-End", "Gestión de Bases de Datos", "Inteligencia Artificial Avanzada", "Optimización de Hardware IA", "Liderazgo y Comunicación", "Orientación Escolar"],
    languagesTitle: "Idiomas",
    languagesList: ["Árabe: Lengua materna", "Francés: Excelente", "Inglés: Excelente", "Español: Principiante"],
    contactTitle: "Contacto",
    contactPhone: "+212 717568270",
    contactEmail: "moatadidrayan7@gmail.com",
    contactLocation: "Mohammedia, Béni Yakhlef",
    commentsTitle: "Comentarios",
    namePlaceholder: "Tu nombre",
    commentPlaceholder: "Tu comentario",
    publishButton: "Publicar",
    instagramLabel: "Instagram",
    linkedinLabel: "LinkedIn",
    footer: "© 2026 Rayan El Moatadide | Todos los derechos reservados"
  }
};
